### ISSUE TITLE
This action is unauthorized

### ISSUE THREAD

**Issue by joealam** [laravel/quickstart-intermediate#10]
When trying to delete a task after following the *Intermediate Task List* guide, I get the following error:
>HttpException in AuthorizesRequests.php line 94:
>This action is unauthorized

This is resolved by including the following in *AuthServiceProvider.php*:
```php
use App\Task;
use App\Policies\TaskPolicy;
```
..which seems to be required to use the `::class` syntax for class name resolution.

Perhaps this should be mentioned in the guide, or the fully qualified class name used directly instead?

**Comment by LukasMa** [comment]
Weird... I cloned the repo and it worked without a problem. I wanted to modify it to do some tests (I renamed everything to fit my needs, I know thats not the normal way to go) and all of a sudden, I get the exact same error as you.

**Comment by carlweis** [comment]
Same issue here, except I already have the use statements for my User and Task model and TaskPolicy. Not sure how to fix this, but it was kind of a bummer to finish the tutorial, just for it not to work.

**Comment by LukasMa** [comment]
Yep, that was my problem, too.

**Comment by AmrAlfoly** [comment]
i had the same problem and i tried all what you have said but the problem was still there
then i solved it by changing 
return $user->id === $task->user_id; 
to 
return $user->id == $task->user_id;
in the 'AuthServiceProvider.php' this solved the problem for me 
the $user->id and the $task->user_id were equal but not identical
$task->user_id was returned as string "1"

**Comment by wedojava** [comment]
@carlweis thank you,Your advice to me inspiration!

1. I changing my class AuthServiceProvider this line:

    App\Task::class => App\Policies\TaskPolicy::class,

to:

    Task::class => TaskPolicy::class,

2. and add this uses on top of AuthServiceProvider.php:

    use App\Policies\TaskPolicy;
    use App\Task;

@AmrAlfoly hi,my code is:

    return $user->id === $task->user_id; 

but nothing wrong. my laravel version is 5.2

**Comment by AmrAlfoly** [comment]
@wedojava  i explained above that $task->user_id was returned as string "1"
and that what made the condition return $user->id === $task->user_id; 
to fail , i don't know why it happened and if there was an explanation i will be glad to hear

**Comment by Craicerjack** [comment]
@joealam Thank you. This was my issue. Its not in docs as of Jan 7th 2016. It should be included for clarities sake.

**Comment by carlweis** [comment]
I agree. I hope this gets added to the docs for anyone new to the framework, following the tutorials.

**Comment by joealam** [comment]
Fixed as of 50a450d901a8eaa00bc0fed81e55055381e2fe81
Documentation has been updated to use the full class name as a string, instead of the `::class` syntax.

**Comment by chapunazar** [comment]
Dear all, after following the tutorial and I found the same issue.. added the necessary Use sentences missing etc and it still failed.. What fixed it was as AmrAlfoly mentioned before the === comparison failed as the types were not identical. Changing it to a == fixed it

**Comment by rdev5** [comment]
Also double check your spelling! Spent almost half an hour tracking this one down:

`public function destory(User $user, Task $task)`

**destory** != destroy

Also, a better fix for the comparison operator would be `$user->id === $task->user->id` I think; this way you can preserve the type checking.

**Comment by lz2510** [comment]
I have the same problem and I resoved it by this method.  Thank you .

**Comment by johnPol** [comment]
@AmrAlfoly 

> i had the same problem and i tried all what you have said but the problem was still there
then i solved it by changing
return $user->id === $task->user_id;
to
return $user->id == $task->user_id;
in the 'AuthServiceProvider.php' this solved the problem for me
the $user->id and the $task->user_id were equal but not identical
$task->user_id was returned as string "1"

Worked for me, thanks)

**Comment by artmonger** [comment]
Changing 
$user->id === $task->user_id
 to 
$user->id == $task->user_id;
worked for me. Thanks.

**Comment by Subhash106** [comment]
Changing 
$user->id === $task->user_id
to 
$user->id == $task->user_id;
worked for me also. Thanks.

**Comment by spotapenko** [comment]
I did next
     
```
 $userId = (string) $user->id;
 $taskUserId = $task->user_id;
 return $userId === $taskUserId;
```

I used it because if you compare  
2 == "2abs" is is TRUE
and
if use  2 === (int) "2abc" it is TRUE

but if compare   (char) 2 === "2abc" - it is FALSE and should be.

**Comment by markokaa** [comment]
great solutions to the problem. why the problem in the first place? if $user->id is 'INT UNSIGNED' and $task->user_id is 'INT UNSIGNED'. what and why is changing it to a string? seems like a bug. thanks @spotapenko for pointing out best comparison.

**Comment by noxue** [comment]
change 
  public function destory(User $user, Task $task) {
        return $user->id === $task->user_id;
    }

to

  public function destroy(User $user, Task $task) {
        return $user->id === $task->user_id;
    }

**Comment by kevsersrca** [comment]
if you use a request and in request you use

```
 public function authorize()
     {
         return false;
     }
```
instead of 

```
 public function authorize()
     {
         return true;
     }
```

**Comment by 2501224066** [comment]
in AuthServiceProvider.php 

 protected $policies = [
        'App\User' => 'App\Policies\UserPolicy',                   <---look it is 'User'  because--|
        User::class => UserPolicy::class,               <-----------------------------it is 'User'--|
    ];
